spring.application.name=admin-service
server.port=${PORT:8080}

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}



#spring.datasource.url=jdbc:postgresql://localhost:5432/Gym_Elite
#spring.datasource.username=postgres
#spring.datasource.password=123456
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

jwt.secret= 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970


logging.level.com.gym=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Core Service Integration
core.app.url=${CORE_APP_URL:http://localhost:8081}
integration.service.url=${INTEGRATION_SERVICE_URL=http://localhost:8082}

internal.api.secret=${INTERNAL_API_SECRET}
