server.port=8080
spring.profiles.active=dev



#spring.datasource.url=jdbc:postgresql://localhost:5432/Gym_Elite
#spring.datasource.username=postgres
#spring.datasource.password=123456
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

jwt.secret= 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970


logging.level.com.gym=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Core Service Integration
core.service.url=http://localhost:8081
integration.service.url=http://localhost:8082

internal.api.secret=9f8e7d6c5b4a3210a1b2c3d4e5f67890abcd1234ef567890abcd1234ef567890
